# Generated by Django 6.0.1 on 2026-03-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacies', '0002_remove_legacy_approved_by_alter_legacy_slug_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='legacy',
            index=models.Index(fields=['status'], name='legacy_status_idx'),
        ),
        migrations.AddIndex(
            model_name='legacy',
            index=models.Index(fields=['status', '-approved_at'], name='legacy_status_approved_idx'),
        ),
        migrations.AddIndex(
            model_name='legacy',
            index=models.Index(fields=['zone', 'status'], name='legacy_zone_status_idx'),
        ),
        migrations.AddIndex(
            model_name='legacy',
            index=models.Index(fields=['-created_at'], name='legacy_created_idx'),
        ),
        migrations.AddIndex(
            model_name='legacy',
            index=models.Index(fields=['-approved_at'], name='legacy_approved_idx'),
        ),
    ]
