# Generated by Django 6.0.1 on 2026-03-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacies', '0003_legacy_legacy_status_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacy',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
