# Generated by Django 6.0.1 on 2026-03-23 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacies', '0004_add_occupation_to_legacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tribute_type', models.CharField(choices=[('candle', 'Candle'), ('message', 'Message')], max_length=10)),
                ('author_name', models.CharField(blank=True, default='', max_length=100)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('legacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tributes', to='legacies.legacy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
