# Generated by Django 6.0.1 on 2026-03-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacies', '0005_tribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacy',
            name='original_language',
            field=models.CharField(choices=[('en', 'English'), ('om', 'Afaan Oromo')], default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='legacy',
            name='story_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='legacy',
            name='story_om',
            field=models.TextField(blank=True, default=''),
        ),
    ]
