# Generated by Django 6.0.1 on 2026-03-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacies', '0006_bilingual_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacy',
            name='relationship_to_person',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
