# Generated by Django 6.0.1 on 2026-07-18 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacies', '0013_add_photo_enhanced_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['event_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('years_label', models.CharField(blank=True, default='', max_length=40)),
                ('years_start', models.IntegerField(blank=True, null=True)),
                ('years_end', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('document', 'Document'), ('newspaper', 'Newspaper Clipping'), ('audio', 'Audio')], max_length=12)),
                ('file', models.FileField(blank=True, null=True, upload_to='legacy_media/')),
                ('external_url', models.URLField(blank=True, default='', max_length=800)),
                ('caption', models.CharField(blank=True, default='', max_length=400)),
                ('caption_om', models.CharField(blank=True, default='', max_length=400)),
                ('media_date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'added_at'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('hrw', 'Human Rights Watch'), ('amnesty', 'Amnesty International'), ('ehrc', 'Ethiopian Human Rights Council'), ('qeerroo', 'Qeerroo Archives'), ('omn', 'OMN'), ('addis_standard', 'Addis Standard'), ('bbc_om', 'BBC Afaan Oromo'), ('voa_om', 'VOA Afaan Oromo'), ('esat', 'ESAT'), ('academic', 'Academic Paper'), ('book', 'Book'), ('family', 'Family Submission'), ('cemetery', 'Cemetery Record'), ('newspaper', 'Newspaper'), ('court', 'Court Document'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=400)),
                ('url', models.URLField(blank=True, default='', max_length=800)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('page_number', models.CharField(blank=True, default='', max_length=40)),
                ('excerpt', models.TextField(blank=True, default='')),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='sources/')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['source_type', 'publication_date'],
            },
        ),
        migrations.AddField(
            model_name='legacy',
            name='alternative_spellings',
            field=models.CharField(blank=True, default='', help_text='Comma-separated alternative name spellings', max_length=400),
        ),
        migrations.AddField(
            model_name='legacy',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legacy',
            name='burial_location',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='legacy',
            name='category',
            field=models.CharField(blank=True, choices=[('fighter', 'Fighter / Combatant'), ('commander', 'Commander / Military Leader'), ('civilian', 'Civilian'), ('political', 'Political Leader'), ('student', 'Student / Youth'), ('journalist', 'Journalist / Writer'), ('intellectual', 'Intellectual / Academic'), ('religious', 'Religious Leader'), ('cultural', 'Cultural Figure'), ('women', "Women's Rights Leader"), ('lawyer', 'Lawyer / Legal Professional'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='legacy',
            name='circumstances',
            field=models.TextField(blank=True, default='', help_text='Circumstances of death or persecution'),
        ),
        migrations.AddField(
            model_name='legacy',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legacy',
            name='death_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legacy',
            name='family_notes',
            field=models.TextField(blank=True, default='', help_text='Known surviving family, relatives'),
        ),
        migrations.AddField(
            model_name='legacy',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=1),
        ),
        migrations.AddField(
            model_name='legacy',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Internal research notes'),
        ),
        migrations.AddField(
            model_name='legacy',
            name='place_of_death',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='legacy',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('partial', 'Partially Verified'), ('verified', 'Fully Verified')], default='unverified', max_length=12),
        ),
        migrations.AddField(
            model_name='legacy',
            name='village',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='legacy',
            name='woreda',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='legacy',
            name='historical_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacies', to='legacies.historicalevent'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='legacies.historicalperiod'),
        ),
        migrations.AddField(
            model_name='legacy',
            name='historical_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacies', to='legacies.historicalperiod'),
        ),
        migrations.AddIndex(
            model_name='legacy',
            index=models.Index(fields=['historical_period', 'status'], name='legacy_period_status_idx'),
        ),
        migrations.AddIndex(
            model_name='legacy',
            index=models.Index(fields=['category', 'status'], name='legacy_category_status_idx'),
        ),
        migrations.AddIndex(
            model_name='legacy',
            index=models.Index(fields=['death_year'], name='legacy_death_year_idx'),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='legacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='legacies.legacy'),
        ),
        migrations.AddField(
            model_name='source',
            name='legacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='legacies.legacy'),
        ),
    ]
